language: ruby
rvm:
- 2.2

cache:
- bundler
- directories:
  - .asset-cache
  - bower_components

before_install:
- nvm install 4
- npm install -g bower svgo
- bower install

script:
- set -e
- bundle exec jekyll build --verbose --trace
- set +e
- cd _site
- touch .nojekyll
- git init
- git config user.name "Travis-CI"
- git config user.email "travis@abemedia.co.uk"
- git add .
- git commit -m "Deployed to Github Pages"
- git push --force --quiet "https://${GH_TOKEN}@github.com/BublitzORG/bublitzorg.github.io" master > /dev/null 2>&1

git:
  depth: 10

notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true